---
title: Vieze luiers
author: Peter Hoffenaar
date: '2017-09-16'
slug: vieze-luiers
categories:
  - Ouders
tags: 
  - Walging
archives: '2017'
---
_‘Wie heeft de wc-bril omhoog laten staan? Hoe vaak moet ik zeggen dat ik er niet met mijn vingers aan wil zitten.’_ 

Vrouwen zijn gevoelig voor urineresten, maar walgen ook eerder van insecten. Twee Slowaakse onderzoekers zagen wel wat in een evolutionaire verklaring. Vrouwen steken van oudsher meer energie in het beschermen van nakomelingen en zouden zo extra alert zijn geworden op besmettingsgevaar. 

Deze theorie voorspelt een verschil tussen vrouwen met en zonder kinderen en in het onderzoek reageerden deze groepen ook anders. Zowel op foto’s van hoofdluizen, teken, vlooien en muggen als ook op stellingen als _‘Ik zorg er altijd voor dat niets van mijn lichaam een openbaar toilet aanraakt’_.  Maar telkens bleken moeders juist minder walgingsgevoelig. Kennelijk ligt het anders en is na poepluiers een wc-bril juist helemaal niet meer zo weerzinwekkend. 

Prokop, P., & Fančovičová, J. (2016). Mothers are less disgust sensitive than childless females. Personality and Individual Differences, 96, 65–69. https://doi.org/10.1016/j.paid.2016.02.064