---
title: Vroegtijdig ingrijpen
author: Peter Hoffenaar
date: '2018-12-18'
slug: vroegtijdig-ingrijpen
categories:
  - Opvoeding
  - Ouders
tags:
  - Pedagogisch advies
  - Hulp
archives: '2018'
---
Hoe eerder, hoe beter. Veel mensen - inclusief Nobelprijswinnaar James Heckman - pleiten voor investeringen in programma’s voor ouders met jonge kinderen. Maar een onderzoeksgroep onder leiding van Francis Gardner van de Oxford universiteit zocht uit of leeftijd inderdaad zo’n doorslaggevende factor is. 

Ze combineerden een meta-analyse op basis van data van individuele gezinnen die deelgenomen hadden aan Europese effectstudies naar _‘Pittige Jaren’_ (Incredible Years) met een traditionele meta-analyse. Zo ontstonden twee datasets, met samen informatie over meer dan 15.000 gezinnen*. 

De effectiviteit verschilde niet voor kinderen tussen een en zes jaar oud en schoolgaande kinderen. Het lijkt tijd voor een nieuw mantra: _‘nooit te vroeg, nooit te laat’_. 

Gardner, F., Leijten, P., Melendez‐Torres, G. J., Landau, S., Harris, V., Mann, J., Beecham, J., Hutchings, J., & Scott, S. (2019). The Earlier the Better? Individual Participant Data and Traditional Meta-analysis of Age Effects of Parenting Interventions. Child Development, 90(1), 7–19. https://doi.org/10.1111/cdev.13138

** In meta-analyses op basis van individuele-patiëntdata (IPD-meta-analyses) worden niet studies op één hoop gegooid, maar individuen. Het bundelen van de ruwe gegevens van alle deelnemers uit meerdere studies vergroot niet alleen de betrouwbaarheid, maar is ook een krachtige methode om inzicht te krijgen in individuele verschillen en groepsverschillen. Zo krijgen we een beter antwoord op de vraag: voor **wie** werkt het?


