---
title: Let op de Benjamin
author: Peter Hoffenaar
date: '2018-05-17'
slug: let-op-de-benjamin
categories:
  - Kinderen
tags:
  - Een tweede kind
  - Plaats in de kinderrij
archives: '2018'
---
Zoonlief zet een grote mond op en dan volgt zijn zus. Kinderen kopiëren uitdagend gedrag, maar met al een onruststoker in het gezin kan de ander ook kiezen voor een rol als vredestichter of brave hendrik. Moeten ouders alert zijn op besmettingsgevaar of rekening houden met steeds grotere verschillen? 

Voor het antwoord maakte Ella Daniel van de Tel Aviv universiteit gebruik van een longitudinale dataset met drie meetmomenten in de vroege kindertijd. Zij stopte alle ouderrapportages over driftkoppigheid in een ingewikkeld model dat ruimte bood voor tweerichtingsverkeer tussen de oudste en de jongste. 

Wat bleek? Als de jongste dwars ligt, vergroot dit de kans dat de oudste zich voorbeeldiger gaat gedragen. Bij weinig problemen met de benjamin lijken ouders zich op te kunnen maken voor strijd met de oudste. 

Daniel, E., Plamondon, A., & Jenkins, J. M. (2018). An Examination of the Sibling Training Hypothesis for Disruptive Behavior in Early Childhood. Child Development, 89(1), 235–247. https://doi.org/10.1111/cdev.12754
