---
title: Een positief label
author: Peter Hoffenaar
date: '2018-12-18'
slug: een-positief-label
categories:
  - Kinderen
tags:
  - Zelfbeeld
  - Milieubewust
archives: '2018'
---
Vertel kinderen hoe milieuvriendelijk ze zijn en ze zullen zich ernaar gaan gedragen. Niet alleen volwassenen, maar ook de jonge consument blijkt vrij simpel te verleiden tot milieuvriendelijke keuzes. 

Karine Charry en Béatrice Parguel zeiden tegen de helft van de kinderen van een Belgische basisschool dat ze uit de tests van een week eerder konden afleiden dat ze respect hadden voor de natuur en aandacht voor duurzaamheid. Vervolgens mochten ze kiezen uit een schrift van een populair merk of eentje van gerecycled papier. 

Twee derde van de scholieren die zojuist bestempeld waren als milieuvriendelijk koos voor het verantwoorde cadeau, terwijl slechts een derde van de controlegroep de sociale druk en uitgekiende marketing kon weerstaan. Kinderen met een uitgekristalliseerd beeld van zichzelf bleken zich eerder te vereenzelvigen met het label en zich ernaar te gedragen dan kinderen met een diffuus zelfbeeld.

Charry, K., & Parguel, B. (2018). Children’s response to “ecofriendly” labelling: The role of self-concept clarity. Journal of Environmental Psychology, 58, 1–7. https://doi.org/10.1016/j.jenvp.2018.07.002