---
title: Televisiegeweld
author: Peter Hoffenaar
date: '2018-09-18'
slug: televisiegeweld
categories:
  - Kinderen
tags:
  - Agressie
  - Beeldscherm
  - Probleemgedrag
archives: '2018'
---
Dat voelt niet goed. Zeker niet als je leest: _'geweld op tv leidt tot hyperactiviteit'_. _‘Oeps, ben ik toch te laks geweest’_, zullen sommige ouders denken. Het scherm als boosdoener gaat erin als zoete koek, maar klopt het wel? 

Nee, blijkt uit een longitudinale studie met 890 jonge deelnemers (4 tot 8 jaar) van Ine Beyens, onderzoeker aan de Amsterdam School of Communication Research (ASCoR). Zij ontdekte dat televisiegeweld gedragskenmerken van ADHD niet versterkt. Maar als het drukke gedrag steeds opvallender wordt, kiezen kinderen wel vaker voor programma’s met gewelddadige scènes. 

Dit resultaat past binnen het idee dat verschillen in zelfregulatie maken dat kinderen wel of geen voorkeur voor mediageweld ontwikkelen.

Beyens, I., Piotrowski, J. T., & Valkenburg, P. M. (2018). Which Came First? Assessing Transactional Relationships Between Children’s Violent Media Use and ADHD-Related Behaviors. Communication Research, 0093650218782300.