---
title: Eau zo cool
author: Peter Hoffenaar
date: '2018-05-17'
slug: eau-zo-cool
categories:
  - Kinderen
tags:
  - Peers
archives: '2018'
---
Om Aruba aan de waterfles te krijgen bracht Saskia Franken op twee scholen in kaart tegen wie leerlingen opkeken. Vanwege hun aanzien werden deze jongeren uitgenodigd voor een training. In anderhalf uur leerden ze over de gezondheidsvoordelen van water en technieken om hun rol als ‘influencer’ goed in te kunnen vullen. 

Twee maanden later bleken de jonge eilandbewoners op deze scholen wel minder zoete drankjes, maar niet meer water te drinken dan op scholen waar geen training was gegeven. Verrassend, omdat dezelfde training in Nederland wel de waterconsumptie had doen stijgen. De auteurs denken dat dit zou kunnen komen doordat in een tropisch klimaat jongeren uit zichzelf al geneigd zijn om veel water drinken. 

Franken, S., Smit, C., & Buijzen, M. (2018). Promoting Water Consumption on a Caribbean Island: An Intervention Using Children’s Social Networks at Schools. International Journal of Environmental Research and Public Health, 15(4), 713. https://doi.org/10.3390/ijerph15040713
