---
title: Koudwatervrees
author: Peter Hoffenaar
date: '2018-05-17'
slug: koudwatervrees
categories:
  - Ouders
tags:
  - Vaders vs. moeders
  - Stress
archives: '2018'
---
Reageren gestreste vaders en moeders anders op babygehuil? De Zwitserse Fabian Probst zocht het uit. Hij liet ouders hun onderarm een minuut in smeltend ijs onderdompelen. Een koud kunstje voor Wim Hof - alias ‘The Iceman’-, maar voor gewone ouders zo onaangenaam dat hun speeksel volliep met het stresshormoon cortisol. 

Andere papa’s en mama’s hadden geluk en kregen warm water. Vervolgens keek iedereen naar videofragmenten met huilende hummeltjes en opnamen waarop de baby zijn tong bewoog of zijn oogjes opende. Telkens was de vraag: _‘Hoe graag wilt u deze baby in uw armen nemen, wiegen en troosten?’_

Alleen gestreste vaders voelden een minder sterke zorgdrang. Mogelijk zijn vechten of vluchten typisch mannelijke reacties op stress. Wegrennen, de wapens oppakken en je kroost in de steek laten waren voor vrouwen in een ver verleden geen opties en zijn dit mogelijk nu nog steeds niet.

Probst, F., Meng-Hentschel, J., Golle, J., Stucki, S., Akyildiz-Kunz, C., & Lobmaier, J. S. (2017). Do women tend while men fight or flee? Differential emotive reactions of stressed men and women while viewing newborn infants. Psychoneuroendocrinology, 75, 213–221. https://doi.org/10.1016/j.psyneuen.2016.11.005