---
title: Slapeloze nachten
author: Peter Hoffenaar
date: '2019-05-18'
slug: slapeloze-nachten
categories:
  - Ouders
tags:
  - Ouderschap
archives: '2019'
---
Tropenjaren worden ze wel genoemd. De eerste jaren met kinderen vereisen een soepele geest in een soepel lichaam om bestand te zijn tegen de scheve balans tussen tegenslagen en triomfen in deze periode. Die weerbaarheid komt in gevaar als een lange en ongestoorde slaap geen vanzelfsprekendheid meer is. 

David Richter van het Duitse instituut voor economisch onderzoek zag dat we best wel weten dat slecht slapen erbij hoort, maar nog niet hoe ernstig de nachtrust van vrouwen én mannen verstoord raakt. En ook niet voor hoe lang. Hij maakte gebruik van enquêtegegevens uit een langlopende longitudinale studie met informatie over de slaaptevredenheid en slaapduur van 2541 vrouwen en 2118 mannen in Duitsland. 

De grafiek voor vrouwen heeft wel wat weg van een zwarte piste. Na een steile afdaling bereiken zij hun dieptepunt op een jaar na de bevalling. Na dit moment is er wel iets van herstel zichtbaar, maar ook **zes jaar later (!)** slapen moeders nog minder goed dan voorheen. Mannen blijft veel van dit alles bespaard, maar ook zij gaan erop achteruit. 

Richter, D., Krämer, M. D., Tang, N. K. Y., Montgomery-Downs, H. E., & Lemola, S. (2019). Long-term effects of pregnancy and childbirth on sleep satisfaction and duration of first-time and experienced mothers and fathers. Sleep, 42(4). https://doi.org/10.1093/sleep/zsz015