---
title: Jonge dichters
author: Peter Hoffenaar
date: '2019-05-18'
slug: jonge-dichters
categories:
  - Kinderen
tags:
  - Gedichten
archives: '2019'
---
Hoewel de getroebleerde tiener van nu kan uitdrukking geven aan zijn gevoelens via emoji’s, worden er nog steeds gedichten geschreven. Een deel van deze zielenroerselen is op internet te vinden.

In plaats van die gedichten woord voor woord te ontleden, concentreerde Will Hipson, promovendus aan de Carleton University in Canada,  zich op het aantal positieve en negatieve gevoelswoorden (sentimentanalyse). 

Van elk van de 8688 gedichten waarvan hij de emotionele toon bepaalde was ook bekend in welk leerjaar de auteur zat. Geheel naar verwachting bleken middelbare scholieren vaker negatieve woorden te gebruiken dan kinderen in de bovenbouw van de basisschool. In de inhoud waren ook verschuivingen te zien, maar opvallende constanten waren _love, day, time, people_, en _friend_.

Zelf ook een keer een gedicht analyseren? Dat kan via de app die Will Hipson ontwikkelde: https://whipson.shinyapps.io/poems_app/

Hipson, W. E. (2019). Using sentiment analysis to detect affect in children’s and adolescents’ poetry. International Journal of Behavioral Development, 43(4), 375–382. https://doi.org/10.1177/0165025419830248
