---
title: Nog even geduld
author: Peter Hoffenaar
date: '2019-12-18'
slug: nog-even-geduld
categories:
  - Kinderen
  - Opvoeding
  - Ouders
tags:
  - Zelfregulatie
archives: '2019'
---
In dit internationale onderzoekproject konden peuters niet kiezen tussen één enkel snoepje nu of een dubbele portie lekkers later (zoals in de welbekende marshmallow-test), maar moesten ze een koekje vier minuten laten liggen voor het te mogen opeten. 

De meeste moeders probeerden hun zoon of dochter te helpen door voor afleiding te zorgen. Dat gebeurde soms in combinatie met liefdevolle woorden, maar een kleine groep werd kwaad of deelde zelfs een uitbrander uit. 

Moeders in Amerika, Turkije, Israël en Roemenië pasten elk van deze strategieën toe, maar Turkse moeders vielen op doordat ze de regel bleven herhalen en met sussende woorden hun kind tot kalmte probeerden te manen: _“Ja, dat koekje is voor jou, maar nu nog even niet”_. 

Desondanks protesteerden de Turkse peuters het hevigst van allemaal. Dit zou volgens de auteurs kunnen komen doordat eerder is gebleken dat hun moeders in het echt minder streng zijn dan in het lab. Maar de ogen van de proefleider zijn voor hun kinderen helemaal geen reden om zich anders te gedragen. Feyza Corapci van de Bogazici Universiteit in Istanbul zag dan ook regelmatig dat er een hapje genomen was. Ze kreeg ook het vaakst te horen dat de lekkernij op miraculeuze wijze verdwenen was.

Friedlmeier, W., Corapci, F., Susa-Erdogan, G., Benga, O., & Kurman, J. (2019). Cultural variations in maternal regulatory responses during a waiting task. Culture and Brain, 7(2), 99–125. https://doi.org/10.1007/s40167-018-0076-0