---
title: Niet zonder slag of stoot
author: Peter Hoffenaar
date: '2019-09-18'
slug: niet-zonder-slag-of-stoot
categories:
  - Kinderen
  - Opvoeding
tags:
  - Agressie
  - Probleemgedrag
archives: '2019'
---
Beloningskaarten en apart zetten helpen om grenzen te stellen en positief gedrag aan te moedigen, maar vragen om vastberadenheid. Het vooruitzicht op een beloning mag dan stimulerend werken, het moet geen stip aan de horizon worden. Het valt dan ook te verwachten dat kinderen tekeergaan als één van de vier stickers waar ze de dag mee begonnen van de kaart verdwijnt. Om diezelfde reden wordt aangeraden alle breekbare voorwerpen te verwijderen van de plek waar het kind zijn straf moet uitzitten. 

Stacy Forcino van de Universiteit van Californië onderzocht hoe vaak 7-12 jarigen in verzet komen. Alle 15 kinderen waren aangemeld voor behandeling van gedragsproblemen. Hun ouders vulden dagelijks in of hun maatregelen gepaard gingen met schoppen, slaan, spugen en het beschadigen van objecten of het eigen lichaam. 

Wat opviel was de enorme variatie. Zo protesteerde Dylan maar 3 van de 16 keer en vooral verbaal, maar liet Rocco 12 van de 18 keer van zich horen en sloeg hij daarbij wild om zich heen. 

Verder bleek dat de aanhouder wint. Een groepsanalyse liet een afname van de gedragsproblemen zien. Maar niet bij iedereen: Rocco bleek één van de vier kinderen zonder behandelsucces. 

Forcino, S. S., Nadler, C. B., & Roberts, M. W. (2019). Parent training for middle childhood conduct problems: Child opposition to timeout and token fines. Practice Innovations, 4(1), 1–12. https://doi.org/10.1037/pri0000090