---
title: School als buffer
author: Peter Hoffenaar
date: '2020-02-18'
slug: school-als-buffer
categories:
  - Opvoeding
  - Kinderen
tags:
  - Peers
  - Thuis en elders
  - School
  - Positief opvoeden
archives: '2020'
---
Een belangrijke vraag is of we de veerkracht van kinderen over- of onderschatten. Bij het [Childhood Adversity and Resilience (C.A.RE)](https://carelab.ucsf.edu/) Lab van de Universiteit van California in San Francisco onderzochten ze de beschermende invloed van de kwaliteit van de leerling-leerkrachtrelatie en sociale status in de klas. 

Voor 338 kinderen tussen de vier en zes jaar oud verzamelden zij:

* peer-nominaties over sociale acceptatie 
* zelfrapportage-gegevens over de leerling-leerkrachtrelatie door middel van een handpopinterview
* de leerkracht-perceptie van de positie in de groep en de relatiekwaliteit

Kinderen die thuis hard werden aangepakt, bleken steeds lastiger en ongehoorzamer te worden als ze afgewezen werden door klasgenoten en ze warmte misten in de relatie met de leerkracht. Maar een hardvochtige opvoeding leidde niet tot meer probleemgedrag als kinderen geaccepteerd werden of een goede band met de leerkracht hadden. Een veilig en positief klasklimaat kan dus het verschil maken voor risicoleerlingen. 

Dit kwam naar voren als de onderzoekers afgingen op de informatie van klasgenoten of het kind zelf, maar niet als ze gebruikmaakten van het leerkrachtoordeel. Hiermee is nog niet duidelijk of kinderen in hoge of geringe mate veerkrachtig zijn, maar is wel helder geïllustreerd dat voor een volledig beeld meerdere informatiebronnen noodzakelijk zijn.

Roubinov, D. S., Boyce, W. T., & Bush, N. R. (2020). Informant-specific reports of peer and teacher relationships buffer the effects of harsh parenting on children’s oppositional defiant disorder during kindergarten. Development and Psychopathology, 32(1), 163–174. https://doi.org/10.1017/S0954579418001499