---
title: Onbedoelde neveneffecten
author: Peter Hoffenaar
date: '2019-02-18'
slug: onbedoelde-neveneffecten
categories:
  - Kinderen
tags:
  - Pesten
  - Peers
archives: '2019'
---
Ook de [NVO](https://www.nvo.nl/) gaat voor 0 uithuisplaatsingen, 0 separaties, 0 thuiszitters! Nul gepeste kinderen klinkt even ambitieus en voor sommigen misschien ook even onrealistisch. Maar met minder genoegen nemen is geen goed idee. 

Er blijkt namelijk zoiets te bestaan als de _‘paradox van de fijne school’_. Succesvolle anti-pestprogramma’s zorgen ervoor dat pestkoppen nog maar een kleine groep vormen en de meerderheid vrolijker naar school gaat, maar helaas raken de overgebleven slachtoffers geïsoleerder en daardoor kwetsbaarder. 

Dat hun positie écht verslechtert blijkt uit onderzoek van Tessa Kaufman en Gijs Huitsing. De kleine groep die twee jaar nadat hun school gestart was met het anti-pestprogramma [KiVa](https://www.kivaschool.nl/) nog steeds gepest werd, was somberder geworden en ging met nog minder zelfvertrouwen naar school. Deze schrijnende situatie laten voortbestaan is voor de Groningse onderzoekers geen optie. Dus pleiten zij ervoor om pesten structureel aan te pakken en pas te spreken van succes als we weten dat iedereen veilig en met meer plezier naar school kan.

Kaufman, T. M. L., & Huitsing, G. (2019). De paradox van de fijne school. Kind en adolescent, 40(1), 94–96. https://doi.org/10.1007/s12453-019-00199-3
