---
title: Opvoedingsstijlen
author: Peter Hoffenaar
date: '2017-05-14'
categories:
  - Opvoeding
  - Ouders
tags:
  - Opvoedingsstijlen
  - Een tweede kind
slug: opvoedingsstijlen
---
Marc Bornstein, Diane Putnick en Joan Suwalsky lieten 61 kersverse moeders spelen met hun vijf maanden oude baby. Vijf maanden na de geboorte van de tweede gooiden zij opnieuw een zak met speelgoed leeg. Sensitiviteit, structuur en niet uit je slof schieten, gaven een hoge score op emotionele beschikbaarheid. Verassend genoeg bleken de scores voor de jongste en oudste niet samen te hangen. Moeders die bij de eerste nog perfect ouderschap lieten zien, leken het bijna verleerd bij de tweede. Ook het omgekeerde kwam voor.

Als opvoedingsgedrag geen constante factor is, heeft het dan nog wel zin om over opvoedingsstijlen te praten? En wijst instabiliteit hier op flexibiliteit omdat het ene kind het andere niet is? De onderzoekers houden zich op de vlakte, maar waarschuwen wel: observaties blijven een momentopname die mogelijk weinig zegt over verleden en toekomst. 

Bornstein, M. H., Putnick, D. L., & Suwalsky, J. T. D. (2016). Emotional Interactions in European American Mother-Infant Firstborn and Secondborn Dyads: A Within-Family Study. Developmental Psychology, 52(9), 1363–1369. https://doi.org/10.1037/dev0000158