---
title: Passende complimenten
author: Peter Hoffenaar
date: '2017-05-14'
slug: passende-complimenten
categories:
  - Ouders
  - Opvoeding
tags: 
  - Positief opvoeden
  - Complimenten
  - Pedagogisch advies
Description: ''
Tags: []
---
Beloon een schoolrapport met passende complimenten. Een zinnig advies, maar kan het kwaad als je dat niet doet? Nou, misschien wel. Bij te positieve woorden kan een kind gestresst raken van het idee dat het volgende rapport net zo mooi moet zijn. En bij een te onderkoelde reactie zou een kind zodanig aan zichzelf kunnen gaan twijfelen dat het schooltaken niet meer goed aandurft. 
Hae In Lee van de Yonsei University in Zuid-Korea vond inderdaad een nadelig effect op stemming en schoolprestaties van zowel buitensporige als te minimale complimenten. Toch lijkt het nog te vroeg om te waarschuwen. Het gaat hier namelijk om een niet-experimentele studie uit het prestatiegerichte Zuid-Korea. 

Lee, H. I., Kim, Y.-H., Kesebir, P., & Han, D. E. (2017). Understanding When Parental Praise Leads to Optimal Child Outcomes: Role of Perceived Praise Accuracy. Social Psychological and Personality Science, 8(6), 679–688. https://doi.org/10.1177/1948550616683020