---
title: Begeerlijk vlees
author: Peter Hoffenaar
date: '2020-02-18'
slug: begeerlijk-vlees
categories:
  - Ouders
tags:
  - Vaders vs. moeders
  - Sekse
archives: '2020'
---
Vrouwen vinden mannen met een buik als een wasbord meestal mooi en sexy, maar associëren gespierdheid ook met dominantie. Vrouwen die kans willen maken op gelijkwaardig ouderschap zien een afgetrainde man daarom minder snel als de toekomstige vader van hun kinderen. Mogelijk kent het ideale ‘papa lichaam’ juist wat overtollig buikvet.

Om dit na te gaan lieten onderzoekers van de University of Southern Mississippi 844 studenten computer-gegenereerde afbeeldingen zien van lichamen met een grotere of kleinere buikomvang. Vervolgens legden ze hen stellingen voor als: _Baby’s doen het hart van deze persoon smelten_ en _Deze persoon probeert zijn kind nieuwe dingen te leren_.

Mannen met een beetje meer vlees werden hoger aangeslagen op ouderschapskwaliteiten dan sportschooltypes. En ook vrouwen met net wat meer vetweefsel werden gezien als betere moeders. De resultaten bevestigen dat je op meerdere manieren aantrekkelijk kunt zijn.  

Sacco, D. F., Holifield, K., Drea, K., Brown, M., & Macchione, A. (2020). Dad and Mom Bods? Inferences of Parenting Ability from Bodily Cues. Evolutionary Psychological Science. https://doi.org/10.1007/s40806-020-00229-x
