---
title: Veerkrachtige ouders
author: Peter Hoffenaar
date: '2017-11-18'
slug: veerkrachtige-ouders
categories:
  - Ouders
  - Opvoeding
tags:
  - Ouderschap
  - Documentaire
archives: '2017'
---
De documentaire [Zorg om Daan](https://www.2doc.nl/speel~KN_1690138~zorg-om-daan-2doc~.html) gaat volgens zijn ouders over een _‘vrolijk zorgenkind’_. Daarmee geven ze blijk van een gebalanceerde kijk op het opvoeden van een kind met een verstandelijke beperking. 

Onderzoekers hebben daarentegen vooral oog gehad voor stress en uitputtingsverschijnselen. Dit terwijl er al sinds 1992 een vragenlijst beschikbaar is voor de positieve kanten. 

Aan de Universiteit van Warwick onderzochten ze in hoeverre deze en andere vragenlijsten positiviteit meten. Ze legden het hele pakket aan 135 moeders voor en vonden vijf indicatoren. Nu nog uitzoeken hoe het komt dat positief denkende moeders in staat zijn om succesvol om te gaan met uitdagende opvoedsituaties. 

Jess, M., Hastings, R. P., & Totsika, V. (2017). The construct of maternal positivity in mothers of children with intellectual disability. Journal of Intellectual Disability Research, 61(10), 928–938. https://doi.org/10.1111/jir.12402