---
title: Vrijetijdsbesteding
author: Peter Hoffenaar
date: '2020-02-18'
slug: vrijetijdsbesteding
categories:
  - Kinderen
  - Opvoeding
tags:
  - Beeldscherm
  - Peers
  - Thuis en elders
archives: '2020'
---
In 2002 maakte [SIRE](https://sire.nl/) een [filmpje](https://youtu.be/W34vo7hGUd0) waarin een jongen een potje voetbal met Richard Witschge afslaat omdat hij naar gitaarles moet. De volgende dag lukt niet vanwege judo en zaterdag is niet mogelijk door zaalvoetbal. In datzelfde jaar stond op Kinderen voor Kinderen 23 het nummer [Recht op vrije tijd](https://youtu.be/YGUnkHDMSPc) met daarin de noodkreet: _‘In 't begin was het nog leuk, maar het leuke is er af. Het leken eerst te gekke hobby's, maar 't lijkt nu wel straf. Dit is niet meer voor de lol. M'n dagen die zijn overvol'_.

Tegenwoordig zien we vooral een gevaar in gamen en sociale media, maar dit Canadese onderzoek neemt alle zorgen over een overvolle agenda en de schermtijd van kinderen weg. Een groep ouders van zes- tot achtjarige kinderen beantwoordde de vraag: _‘Wat deed uw kind vandaag?’_ Voor ieder tijdblok van twee uur schreven zij op wat het kind aan het doen was, waar dat gebeurde en met wie. 
Meer dan de helft van de tijd vulden kinderen zelf in. Zij speelden dan vaak met lego, auto’s of poppen (44%), maar kozen af en toe ook voor gamen of TikTok (14%). De hoeveelheid schermtijd valt dus mee. En dan bleek ook nog eens dat kinderen in de helft van de gevallen samen met een ander achter de tablet, tv, telefoon of spelcomputer zaten. 

De resterende uren gingen weliswaar op aan door ouders voorgekauwde activiteiten, maar dan wel vooral aan onvermijdbare dingen als eten, familiebezoek of een kinderfeestje (36%) en niet zozeer aan sport, muziek of hobby’s (6%). 

Archbell, K. A., Coplan, R. J., & Rose-Krasnor, L. (2020). What did your child do today? Describing young children’s daily activities outside of school. Journal of Early Childhood Research, 18(2), 189–199. https://doi.org/10.1177/1476718X19898724