---
title: Gokkers
author: Peter Hoffenaar
date: '2017-09-16'
slug: gokkers
categories:
  - Kinderen
tags:
  - Verslaving
archives: '2017'
---
Een groepje jongeren hangt rond bij een gokkast. Ze verspelen ieder wat euro’s. Dan grijpt de ‘echte’ gokker zijn kans. Hij weet zeker dat de machine nu op ‘geven’ staat. Gaat het hier om iemand die het magisch denken niet los heeft kunnen laten of om een depressieve jongere die verstrikt is geraakt in de slimme netten van de gokindustrie? Mogelijk allebei.

Zo vonden Italiaanse psychologen dat problematisch gokgedrag samengaat met de neiging om invloed toe te schrijven aan je eigen gedachten. Gokkers gaan dus niet uit van willekeur, maar voelen zich verantwoordelijk voor winst en verlies.

Maar door slimme trucjes hebben ze vaak niet eens door dat ze verliezen. Bij fruitautomaten met meerdere winlijnen gaan bij drie ananassen op rij de lampjes wel flikkeren en het geluid aan, maar is het netto resultaat doorgaans negatief. De spelers hebben niks in de gaten. Die rammen net zo hard op de knop als bij echte winst.
Sommigen gaan zo op in het spel dat ze elk besef van tijd verliezen. ‘Dark flow’ noemt Mike Dixon van het Gambling Research Lab in Waterloo deze toestand en het komt vaker voor bij depressieve jongeren. Vermoedelijk zijn ze even hun somberheid kwijt en overheerst de positieve, maar irrationele gedachte dat voorgevoelens realiteit kunnen worden.

Passanisi, A., Craparo, G., & Pace, U. (2017). Magical thinking and decision-making strategies among late adolescent regular gamblers: A mediation model. Journal of Adolescence, 59, 51–58. https://doi.org/10.1016/j.adolescence.2017.05.016