---
title: Kieskeurige eters
author: Peter Hoffenaar
date: '2017-09-16'
slug: kieskeurige-eters
categories:
  - Kinderen
  - Opvoeding
  - Ouders
tags:
  - Eten
  - Probleemgedrag
  - Thuis en elders
archives: '2017'
---
In de vorige eeuw deed Judith Harris flink wat stof opwaaien met ‘Het misverstand opvoeding’. Hierin stelde zij dat socialisatie context-specifiek is en dat kinderen zich dus op een kinderdagverblijf heel anders kunnen gedragen dan thuis. Geldt dat ook voor wat ze wel en niet eten? 

Onderzoekers aan de University of Illinois bogen zich over deze onopgeloste kwestie. Ze pakten het een beetje anders aan dan gebruikelijk. Zo vroegen ze niet om een lijstje met gruwelgroenten, maar gingen ze kijken wat kinderen deden als de warme maaltijd niet in de smaak viel. Ze turfden hoe vaak kinderen luid protesteerden of beleefd om iets anders vroegen, maar telden ook de keren dat de zo gehate kaas plotsklaps op het bord van een ander lag. 

Het eetgedrag thuis en onder toezicht van een gastouder bleek vergelijkbaar, maar kinderen in de reguliere opvang waren thuis veel kieskeuriger. Misschien is het tijd om dat verkleurde boek van Harris weer eens uit de kast te halen?

Luchini, V., Musaad, S., Lee, S.-Y., & Donovan, S. M. (2017). Observed differences in child picky eating behavior between home and childcare locations. Appetite, 116, 123–131. https://doi.org/10.1016/j.appet.2017.04.021