---
title: Gedoemd te mislukken
author: Peter Hoffenaar
date: '2018-09-18'
slug: gedoemd-te-mislukken
categories:
  - Ouders
tags:
  - Hulp
archives: '2018'
---
Voor hulp aan kinderen is ouderlijke toestemming vereist (artikel 6 van de [NVO-beroepscode](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwie6ajv-bzpAhXD16QKHcDvAVkQFjAAegQIAxAB&url=https%3A%2F%2Fwww.nvo.nl%2Fbestanden%2FBeroepscode%2F840-1%2FBeroepscode_web.pdf&usg=AOvVaw3iYswJeg9ipo7cFKa7Qm7E)). 

Een simpel ‘ja’ of ‘nee’ volstaat, maar Jessica Schleider en John Weisz laten zien dat het loont om ouders ook te vragen naar hun overtuigingen. Zij plaatsten een oproep op Amazon’s _MTurk_, een platform waar bezoekers terecht kunnen voor betaalde klusjes. 

Ruim tweehonderd ouders reageerden en beantwoordden vragen waaruit op te maken viel hoe overtuigd ze waren dat je van fouten kunt leren en gevoelens te beïnvloeden zijn. Ook kregen zij de opdracht zich te verplaatsen in de denkbeeldige situatie dat hun kind worstelde met angst of depressieve gevoelens. 

Ouders die incidenteel falen, beschouwen dit als leerzaam en hebben meer vertrouwen in de hulpverlening. Uit een tweede studie bleek dat negatieve gedachtekronkels om te buigen zijn. Alle reden dus om het gesprek aan te gaan!

Schleider, J. L., & Weisz, J. R. (2018). Parent Expectancies and Preferences for Mental Health Treatment: The Roles of Emotion Mind-Sets and Views of Failure. Journal of Clinical Child & Adolescent Psychology, 47(sup1), S480–S496. [PDF](http://www.schleiderlab.org/uploads/2/1/8/4/21847128/schleider_weisz_2018_-_in_press_jccap.pdf)