---
title: Goede en slechte vormen van slaan?
author: Peter Hoffenaar
date: '2018-09-18'
slug: goede-en-slechte-vormen-van-slaan
categories:
  - Opvoeding
  - Ouders
tags:
  - Pedagogische tik
  - Straffen
  - Opvoedingsstijlen
archives: '2018'
---
Het televisieprogramma [Netwerk](https://tvblik.nl/netwerk/18-september-2009) vroeg in 2009 aan 516 ouders hoe vaak zij een corrigerende tik gaven. Vijf procent antwoordde ‘regelmatig’ en driekwart ‘een enkele keer’. Twee jaar later bleek in een SCP-onderzoek 15% het eens met de stelling _‘Meestal geef ik mijn kind een draai om de oren of een tik als hij/zij iets doet wat niet mag’_. 

Andere vraag, andere uitkomsten? Dat principe lijkt inderdaad op te gaan. Zo was 88% van de 3148 Canadese moeders in het onderzoek van Marie-Ève Clément en Claire Chamberland van mening dat een corrigerende tik geen effectieve manier van opvoeden is. 

En nu blijkt ook woordkeuze effect te hebben. Alan Brown laat overtuigend zien dat billenkoek en een klap geven ouders nauwelijks zorgen baren, maar dat een uithaal en een draai om de oren wel problematisch klinken. Ouders kunnen dus een term kiezen die de werkelijkheid verbloemt, bijvoorbeeld _‘pedagogische tik’_. Daarmee is uiteraard geenszins het leed voor kinderen verzacht.

Brown, A. S., Holden, G. W., & Ashraf, R. (2018). Spank, slap, or hit? How labels alter perceptions of child discipline. Psychology of Violence, 8(1), 1–9. https://doi.org/10.1037/vio0000080

Clément, M.-È., & Chamberland, C. (2009). The Role of Parental Stress, Mother’s Childhood Abuse and Perceived Consequences of Violence in Predicting Attitudes and Attribution in Favor of Corporal Punishment. Journal of Child and Family Studies, 18(2), 163–171. https://doi.org/10.1007/s10826-008-9216-z